
name = "2xBHI_aether_medium_l1pretrain"
model_type = "image"
scale = 2
use_amp = true
bfloat16 = true
fast_matmul = true

[datasets.train]
type = "paired"
dataroot_gt = '/home/phhofm/Documents/datasets/bhi_small/BHI_small'
dataroot_lq = '/home/phhofm/Documents/datasets/bhi_small/x2'
patch_size = 64
batch_size = 8

[datasets.val]
name = "val"
type = "paired"
dataroot_gt = '/home/phhofm/Documents/datasets/bhi_small/BHI100/HR'
dataroot_lq = '/home/phhofm/Documents/datasets/bhi_small/BHI100/x2'
[val]
val_freq = 10000
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
[val.metrics.dists]
type = "calculate_dists"
better = "lower"
[val.metrics.topiq]
type = "calculate_topiq"

[path]

[network_g]
#type = "aether_small"
type = "aether_medium"
#type = "aether_large"

[train]
ema = 0.999

[train.optim_g]
type = "adamw"
lr = 2e-4
betas = [ 0.9, 0.99 ]
weight_decay = 0

#  losses
[train.pixel_opt]
type = "L1Loss"
loss_weight = 1.0
reduction = "mean"

[logger]
total_iter = 1000000
save_checkpoint_freq = 10000
use_tb_logger = true
